language: node_js
node_js:
  - 10
directories:
  - node_modules
env:
  - CI=true
install: npm ci
script: skip

jobs:
  include:
    - stage: test & lint
      script: npm run test
      script: npm run lint

    - stage: Github Pages release
      if: branch = master
      script: npm run build-storybook
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $github_token
        local_dir: docs

    - state: Npm release
      deploy:
        provider: npm
        email: yuhanlin1105@gmail.com
        api_key: $npm_token
        skip_cleanup: true
        on:
          tags: true
